package com.civstudio.server.command;

import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * A {@link CommandStore} backed by a SQL table via {@link JdbcTemplate}. The schema is created
 * on first use with {@code CREATE TABLE IF NOT EXISTS} (portable across H2 and PostgreSQL), so
 * it is safe to point at a shared database — it touches only its own {@code session_command}
 * table. Rows are ordered by an identity id, which preserves submission order (and hence tie
 * order among same-tick commands, matching {@link CommandLog#drainDueBy(long)}).
 */
public final class JdbcCommandStore implements CommandStore {

	private final JdbcTemplate jdbc;
	private final CommandCodec codec;

	public JdbcCommandStore(JdbcTemplate jdbc, CommandCodec codec) {
		this.jdbc = jdbc;
		this.codec = codec;
	}

	/** Create the table + index if absent. Portable DDL (H2 + PostgreSQL). */
	public void initSchema() {
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS session_command (
				  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  session_id VARCHAR(160) NOT NULL,
				  tick       BIGINT NOT NULL,
				  type       VARCHAR(64) NOT NULL,
				  payload    VARCHAR(4000) NOT NULL,
				  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
				)""");
		jdbc.execute("CREATE INDEX IF NOT EXISTS idx_session_command_session "
				+ "ON session_command(session_id, id)");
	}

	@Override
	public void append(String sessionId, GameCommand command) {
		jdbc.update("INSERT INTO session_command(session_id, tick, type, payload) VALUES (?, ?, ?, ?)",
				sessionId, command.tick(), codec.type(command), codec.payload(command));
	}

	@Override
	public List<GameCommand> load(String sessionId) {
		return jdbc.query(
				"SELECT tick, type, payload FROM session_command WHERE session_id = ? ORDER BY id",
				(rs, rowNum) -> codec.decode(rs.getString("type"), rs.getLong("tick"),
						rs.getString("payload")),
				sessionId);
	}
}
