package com.civstudio.settlement;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;
import java.util.zip.GZIPOutputStream;

import com.civstudio.geo.PlotGeo;
import com.civstudio.geo.PlotType;
import com.civstudio.geo.TerrainRegistry;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * Persists a province's generated plot field to {@code map/provinces/<id>.json} and loads
 * it back, so the (expensive) per-tile generation is paid <b>once</b> and the canonical
 * field is reused by every run. Because the field is now generated seed-independently
 * (see {@link com.civstudio.util.RngSeed#forProvinceCanonical}), the persisted file always
 * equals what any run would produce — a province's geography is a property of the map, not
 * of a particular run (see {@code docs/province-plots.md}).
 * <p>
 * A plot is stored as its raster position, river code, and the Civ4 type keys of its
 * terrain / relief / feature / bonus (resolved back through the {@link TerrainRegistry} on
 * load). The record is <b>gzip-compressed JSON</b> ({@code <id>.json.gz}) — the field is
 * highly repetitive (repeated type keys and field names), so gzip shrinks it ~25&times; over
 * plain JSON while staying trivially (de)serialized.
 * <p>
 * Fields are read from and written to <b>one shared cache</b>: {@code <cacheRoot>/v<MAP_VERSION>/},
 * where {@code cacheRoot} defaults to {@code .map} and is {@linkplain #configure overridden}
 * by the server to its {@code civstudio.plots.cache-dir} (the persistent volume in prod). This is
 * the <b>same directory and byte-identical file format</b> the server's on-demand
 * {@code PlotService} uses, so the sim (colony founding, caravan crossings) and the web plot feed
 * share one cache: a province generated by either is reused by the other, never generated twice or
 * stored in two places. The cache is a working-dir/volume folder — the store never writes into the
 * source tree (it used to write {@code src/main/resources/map/provinces}, which polluted the repo
 * and duplicated the server cache). A missing field is regenerated on demand.
 * <p>
 * The directory is <b>versioned by {@link #MAP_VERSION}</b>, so a change to plot generation (a
 * {@code MAP_VERSION} bump) points the cache at a fresh, empty dir and every province regenerates
 * lazily — otherwise the sim would keep loading a <em>stale</em> field while the map served the
 * freshly-generated one, and the founded colony's siting would silently disagree with the terrain.
 */
public final class ProvincePlotStore {

	/**
	 * The plot <b>generation version</b>: bump this whenever a change to plot generation alters the
	 * output a province yields — {@code ProvincePlotField} / {@code CityPlacement} / {@code
	 * TerrainGenerator} / bonus placement / a {@code terrains.json} yield, etc. It versions both the
	 * server's on-disk plot cache (a new version → a fresh cache dir, old one orphaned) and the
	 * client's {@code /api/plots/{id}?v=} URL (a new version → a browser-cache miss), so a
	 * generation change reaches every client instead of being masked by an immutably-cached grid.
	 * The web bundle ships it as {@code mapVersion} (also an MCP tool, {@code get_map_version}). See
	 * {@code docs/plot-serving.md}.
	 */
	public static final int MAP_VERSION = 9; // 9: sea-rooted river drainage — flow points seaward + a render width class per plot (docs/river-rendering.md §3/§4); 8: urban is an overlay flag on natural terrain (retired TERRAIN_URBAN ground — docs/urban-plots.md); 7: real-world plot place names (GeoNames); 6: water-dominant urban-core siting

	// The cache root — a working-dir/volume folder, NOT the source tree. Defaults to .map
	// (matching PlotService's civstudio.plots.cache-dir default) and is overridden by the server via
	// configure(...) so the sim and the web plot feed share exactly one cache. The MAP_VERSION
	// subdir orphans stale fields on a generation bump.
	private static final String DEFAULT_CACHE_ROOT = ".map";
	private static volatile String cacheRoot = DEFAULT_CACHE_ROOT;
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/**
	 * Point the plot-field cache at {@code cacheRoot} (the server pushes its
	 * {@code civstudio.plots.cache-dir} here at startup, so the sim shares the same cache as the
	 * on-demand {@code PlotService}). The versioned {@code <cacheRoot>/v<MAP_VERSION>} subdir is
	 * derived from it. Mirrors {@code AnbennarFiles.configure}. A blank/null value is ignored.
	 */
	public static void configure(String cacheRoot) {
		if (cacheRoot != null && !cacheRoot.isBlank())
			ProvincePlotStore.cacheRoot = cacheRoot;
	}

	/** The versioned cache directory fields are read from / written to ({@code <root>/v<GEN>}). */
	public static File writeDir() {
		return new File(cacheRoot, "v" + MAP_VERSION);
	}

	// gzipped-JSON file name for a province
	private static String fileName(int provinceId) {
		return provinceId + ".json.gz";
	}

	private ProvincePlotStore() {
	}

	/**
	 * One persisted plot — the {@link Plot}'s {@link PlotGeo raster scalars} (kept flat, so the
	 * JSON the web reads is unchanged) plus its terrain/relief/feature/bonus as Civ4 type keys.
	 * The object&harr;key mapping lives here in {@link #of}/{@link #toPlot} rather than scattered
	 * through {@code save}/{@code load}, so adding a field is a one-record change.
	 */
	private record StoredPlot(int x, int y, int river, String terrain, String plotType,
			String feature, String bonus, int elevation, int coast, String name,
			// the built-up urban-core overlay flag (natural terrain kept underneath). Always
			// serialized (a missing primitive can't round-trip through Jackson 3's record creator);
			// "urban":false is a constant repeated token, so gzip all but erases it in the cache.
			boolean urban) {

		/** The persisted form of a runtime plot: its raster scalars + its type keys + its place name. */
		static StoredPlot of(Plot p) {
			PlotGeo g = p.geo();
			return new StoredPlot(g.x(), g.y(), g.river(), p.terrain().type(), p.plotType().name(),
					p.feature() == null ? null : p.feature().type(),
					p.bonus() == null ? null : p.bonus().type(), g.elevation(), g.coast(),
					p.placeName(), p.urban());
		}

		/** Resolve back to a runtime plot, looking the type keys up in {@code registry}. */
		Plot toPlot(TerrainRegistry registry) {
			Plot p = new Plot(new PlotGeo(x, y, river, elevation, coast),
					registry.terrain(terrain), PlotType.valueOf(plotType),
					feature == null ? null : registry.feature(feature),
					bonus == null ? null : registry.bonus(bonus));
			p.setPlaceName(name); // null for caches written before the naming pass existed
			p.setUrban(urban);    // false for caches written before urban became an overlay flag
			return p;
		}
	}

	/**
	 * Load a province's persisted plot field, or {@code null} if none is stored yet.
	 *
	 * @param provinceId the province id
	 * @param registry   the terrain/feature/bonus registry to resolve the type keys
	 * @return the plots, or {@code null} if the province has not been persisted
	 */
	public static List<Plot> load(int provinceId, TerrainRegistry registry) {
		try (InputStream in = open(provinceId)) {
			if (in == null)
				return null;
			List<StoredPlot> stored = MAPPER.readValue(in,
					new TypeReference<List<StoredPlot>>() {
					});
			List<Plot> plots = new ArrayList<>(stored.size());
			for (StoredPlot sp : stored)
				plots.add(sp.toPlot(registry));
			return plots;
		} catch (IOException e) {
			throw new UncheckedIOException(
					"failed to load persisted plot field for province " + provinceId, e);
		}
	}

	/**
	 * Serialize a plot field to its persisted form: the gzip-compressed JSON blob (the exact bytes
	 * {@link #save} writes and the web viewer gunzips). Used by the server to generate a province's
	 * plot grid on demand and serve / cache it without going through the fixed {@link #WRITE_DIR}
	 * (see {@code docs/plot-serving.md}).
	 *
	 * @param plots the generated plots to serialize
	 * @return the gzipped-JSON bytes
	 */
	public static byte[] toGzBytes(List<Plot> plots) {
		List<StoredPlot> stored = new ArrayList<>(plots.size());
		for (Plot p : plots)
			stored.add(StoredPlot.of(p));
		ByteArrayOutputStream bos = new ByteArrayOutputStream();
		try (OutputStream out = new GZIPOutputStream(bos)) {
			MAPPER.writeValue(out, stored);
		} catch (IOException e) {
			throw new UncheckedIOException("failed to serialize plot field", e);
		}
		return bos.toByteArray();
	}

	/**
	 * Persist a province's generated plot field to the shared cache
	 * ({@code <cacheRoot>/v<MAP_VERSION>/<id>.json.gz}), so a later run — or the server's
	 * {@code PlotService} sharing the same dir — reuses it.
	 *
	 * @param provinceId the province id
	 * @param plots      the generated plots to store
	 */
	public static void save(int provinceId, List<Plot> plots) {
		try {
			File dir = writeDir();
			dir.mkdirs();
			Files.write(new File(dir, fileName(provinceId)).toPath(), toGzBytes(plots));
		} catch (IOException e) {
			throw new UncheckedIOException(
					"failed to persist plot field for province " + provinceId, e);
		}
	}

	// the persisted field's decompressed stream from the shared cache, or null if not cached yet.
	// The stored form is gzipped JSON, so the raw stream is wrapped in GZIP.
	private static InputStream open(int provinceId) throws IOException {
		File f = new File(writeDir(), fileName(provinceId));
		if (f.exists())
			return new GZIPInputStream(Files.newInputStream(f.toPath()));
		return null;
	}
}
