package com.civstudio.server.registry;

import java.util.List;
import java.util.Optional;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

/**
 * The durable registry: runs and their seats in the actual database.
 * <p>
 * Owns exactly two tables, created on first use with {@code CREATE TABLE IF NOT EXISTS} and portable
 * across H2 and PostgreSQL — the house style of {@code JdbcCommandStore} / {@code JdbcChatStore},
 * so it is safe to point at a shared database: it touches nothing but its own.
 * <p>
 * <b>One seat per player is a {@code UNIQUE} constraint</b>, not a check in application code. That
 * is the point of this class: the rule then holds across restarts and concurrent joins, rather than
 * resting on a live map that a redeploy throws away.
 * <p>
 * The design sketch's separate {@code timeline} table is deliberately absent: a Timeline <em>is</em>
 * a session (its scenario), and its winner is its {@code end_reason} — a second table would say the
 * same things and need keeping in step with this one.
 */
public final class JdbcSessionRegistry implements SessionRegistry {

	private final JdbcTemplate jdbc;

	public JdbcSessionRegistry(JdbcTemplate jdbc) {
		this.jdbc = jdbc;
	}

	/** Create the tables + index if absent. Portable DDL (H2 + PostgreSQL). */
	public void initSchema() {
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS game_session (
				  id          VARCHAR(160) PRIMARY KEY,
				  scenario    VARCHAR(64)  NOT NULL,
				  seed        BIGINT       NOT NULL,
				  province_id INT          NOT NULL,
				  owner       VARCHAR(160),
				  state       VARCHAR(32)  NOT NULL,
				  end_reason  VARCHAR(1000),
				  tick        BIGINT       NOT NULL DEFAULT 0,
				  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
				  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
				)""");
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS session_seat (
				  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  session_id  VARCHAR(160) NOT NULL,
				  user_id     VARCHAR(160) NOT NULL,
				  colony_name VARCHAR(160) NOT NULL,
				  province_id INT          NOT NULL,
				  seat_order  INT          NOT NULL,
				  seated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
				  CONSTRAINT uq_session_seat_player UNIQUE (session_id, user_id)
				)""");
		jdbc.execute("CREATE INDEX IF NOT EXISTS idx_session_seat_session "
				+ "ON session_seat(session_id, seat_order)");
	}

	@Override
	public void save(SessionRecord r) {
		// upsert without MERGE/ON CONFLICT: the two dialects spell those differently, and a run is
		// saved once at founding and updated by updateProgress, so the race this loses to cannot
		// happen (SessionHost.create is synchronized on the same id)
		int updated = jdbc.update("""
				UPDATE game_session SET scenario = ?, seed = ?, province_id = ?, owner = ?,
				  state = ?, end_reason = ?, tick = ?, updated_at = CURRENT_TIMESTAMP
				WHERE id = ?""",
				r.scenario(), r.seed(), r.provinceId(), r.owner(), r.state(), r.endReason(),
				r.tick(), r.id());
		if (updated == 0)
			jdbc.update("""
					INSERT INTO game_session(id, scenario, seed, province_id, owner, state, end_reason, tick)
					VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
					r.id(), r.scenario(), r.seed(), r.provinceId(), r.owner(), r.state(),
					r.endReason(), r.tick());
	}

	@Override
	public void updateProgress(String id, String state, String endReason, long tick) {
		jdbc.update("""
				UPDATE game_session SET state = ?, end_reason = ?, tick = ?,
				  updated_at = CURRENT_TIMESTAMP
				WHERE id = ?""", state, endReason, tick, id);
	}

	@Override
	public Optional<SessionRecord> find(String id) {
		return jdbc.query("SELECT * FROM game_session WHERE id = ?", MAPPER, id).stream().findFirst();
	}

	@Override
	public List<SessionRecord> all() {
		return jdbc.query("SELECT * FROM game_session ORDER BY created_at, id", MAPPER);
	}

	@Override
	public void seat(SeatRecord s) {
		try {
			jdbc.update("""
					INSERT INTO session_seat(session_id, user_id, colony_name, province_id, seat_order)
					VALUES (?, ?, ?, ?, ?)""",
					s.sessionId(), s.userId(), s.colonyName(), s.provinceId(), s.seatOrder());
		} catch (DuplicateKeyException already) {
			// the UNIQUE constraint did its job — two joins raced, or a player asked twice
			throw new SeatTakenException(s.userId() + " already holds a seat in " + s.sessionId());
		}
	}

	@Override
	public List<SeatRecord> seats(String sessionId) {
		return jdbc.query("SELECT * FROM session_seat WHERE session_id = ? ORDER BY seat_order",
				SEAT_MAPPER, sessionId);
	}

	@Override
	public Optional<SeatRecord> seatOf(String sessionId, String userId) {
		return jdbc.query("SELECT * FROM session_seat WHERE session_id = ? AND user_id = ?",
				SEAT_MAPPER, sessionId, userId).stream().findFirst();
	}

	private static final RowMapper<SessionRecord> MAPPER = (rs, n) -> new SessionRecord(
			rs.getString("id"), rs.getString("scenario"), rs.getLong("seed"),
			rs.getInt("province_id"), rs.getString("owner"), rs.getString("state"),
			rs.getString("end_reason"), rs.getLong("tick"));

	private static final RowMapper<SeatRecord> SEAT_MAPPER = (rs, n) -> new SeatRecord(
			rs.getString("session_id"), rs.getString("user_id"), rs.getString("colony_name"),
			rs.getInt("province_id"), rs.getInt("seat_order"));
}
