package com.civstudio.server.registry;

import java.util.List;
import java.util.Optional;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import com.civstudio.server.Outcome;

/**
 * The durable registry: runs and their seats in the actual database.
 * <p>
 * Owns exactly two tables, created on first use with {@code CREATE TABLE IF NOT EXISTS} and portable
 * across H2 and PostgreSQL — the house style of {@code JdbcCommandStore} / {@code JdbcChatStore},
 * so it is safe to point at a shared database: it touches nothing but its own.
 * <p>
 * <b>One seat per player is a {@code UNIQUE} constraint</b>, not a check in application code. That
 * is the point of this class: the rule then holds across restarts and concurrent joins, rather than
 * resting on a live map that a redeploy throws away.
 * <p>
 * <b>Session taxonomy + the state split</b> (see {@code docs/session-management.md}): a run carries
 * {@code kind}/{@code mode}/{@code difficulty} (what it is) and {@code clock_state}/{@code outcome}
 * (where it got to, split out of the old single {@code state}). {@link #initSchema()} migrates a table
 * created before those columns with {@code ADD COLUMN IF NOT EXISTS} + a backfill, and the legacy
 * {@code state} column is <b>kept written</b> as a derived mirror so a rollback to pre-split code still
 * reads the table (expand-and-contract).
 */
public final class JdbcSessionRegistry implements SessionRegistry {

	private final JdbcTemplate jdbc;

	public JdbcSessionRegistry(JdbcTemplate jdbc) {
		this.jdbc = jdbc;
	}

	/** Create the tables + index if absent, and migrate an older {@code game_session} in place. */
	public void initSchema() {
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS game_session (
				  id          VARCHAR(160) PRIMARY KEY,
				  scenario    VARCHAR(64)  NOT NULL,
				  seed        BIGINT       NOT NULL,
				  province_id INT          NOT NULL,
				  owner       VARCHAR(160),
				  state       VARCHAR(32)  NOT NULL,
				  kind        VARCHAR(32),
				  mode        VARCHAR(64),
				  difficulty  VARCHAR(64),
				  clock_state VARCHAR(32),
				  outcome     VARCHAR(32),
				  end_reason  VARCHAR(1000),
				  tick        BIGINT       NOT NULL DEFAULT 0,
				  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
				  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
				)""");
		// migrate a table created before the taxonomy + state split. ADD COLUMN IF NOT EXISTS is a
		// no-op on a freshly-created table (which already has them) and portable across H2 + PostgreSQL.
		jdbc.execute("ALTER TABLE game_session ADD COLUMN IF NOT EXISTS kind        VARCHAR(32)");
		jdbc.execute("ALTER TABLE game_session ADD COLUMN IF NOT EXISTS mode        VARCHAR(64)");
		jdbc.execute("ALTER TABLE game_session ADD COLUMN IF NOT EXISTS difficulty  VARCHAR(64)");
		jdbc.execute("ALTER TABLE game_session ADD COLUMN IF NOT EXISTS clock_state VARCHAR(32)");
		jdbc.execute("ALTER TABLE game_session ADD COLUMN IF NOT EXISTS outcome     VARCHAR(32)");
		// backfill legacy rows from the retained `state`. kind: the old owner/scenario coincidence,
		// made explicit. clock_state: state, except GAME_OVER which was a stopped thread. outcome: a
		// GAME_OVER row's verdict is unrecoverable from the old columns, so it reads LOST (finished);
		// everything else is LIVE (undecided / restorable).
		jdbc.update("""
				UPDATE game_session SET kind = CASE
				  WHEN scenario = 'timeline' THEN 'TIMELINE'
				  WHEN owner IS NULL THEN 'DEMO'
				  ELSE 'SINGLE_PLAYER' END
				WHERE kind IS NULL""");
		jdbc.update("UPDATE game_session SET clock_state = CASE WHEN state = 'GAME_OVER' THEN 'STOPPED' "
				+ "ELSE state END WHERE clock_state IS NULL");
		jdbc.update("UPDATE game_session SET outcome = CASE WHEN state = 'GAME_OVER' THEN 'LOST' "
				+ "ELSE 'LIVE' END WHERE outcome IS NULL");
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS session_seat (
				  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  session_id  VARCHAR(160) NOT NULL,
				  user_id     VARCHAR(160) NOT NULL,
				  colony_name VARCHAR(160) NOT NULL,
				  province_id INT          NOT NULL,
				  seat_order  INT          NOT NULL,
				  seated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
				  CONSTRAINT uq_session_seat_player UNIQUE (session_id, user_id)
				)""");
		jdbc.execute("CREATE INDEX IF NOT EXISTS idx_session_seat_session "
				+ "ON session_seat(session_id, seat_order)");
	}

	@Override
	public void save(SessionRecord r) {
		// upsert without MERGE/ON CONFLICT: the two dialects spell those differently, and a run is
		// saved once at founding and updated by updateProgress, so the race this loses to cannot
		// happen (SessionHost.create is synchronized on the same id)
		int updated = jdbc.update("""
				UPDATE game_session SET scenario = ?, seed = ?, province_id = ?, owner = ?,
				  state = ?, kind = ?, mode = ?, difficulty = ?, clock_state = ?, outcome = ?,
				  end_reason = ?, tick = ?, updated_at = CURRENT_TIMESTAMP
				WHERE id = ?""",
				r.scenario(), r.seed(), r.provinceId(), r.owner(), r.legacyState(), r.kind(), r.mode(),
				r.difficulty(), r.clockState(), r.outcome(), r.endReason(), r.tick(), r.id());
		if (updated == 0)
			jdbc.update("""
					INSERT INTO game_session(id, scenario, seed, province_id, owner, state, kind, mode,
					  difficulty, clock_state, outcome, end_reason, tick)
					VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
					r.id(), r.scenario(), r.seed(), r.provinceId(), r.owner(), r.legacyState(), r.kind(),
					r.mode(), r.difficulty(), r.clockState(), r.outcome(), r.endReason(), r.tick());
	}

	@Override
	public void updateProgress(String id, String clockState, String outcome, String endReason,
			long tick) {
		jdbc.update("""
				UPDATE game_session SET clock_state = ?, outcome = ?, state = ?, end_reason = ?, tick = ?,
				  updated_at = CURRENT_TIMESTAMP
				WHERE id = ?""", clockState, outcome, legacyStateOf(clockState, outcome), endReason, tick, id);
	}

	// the legacy five-value `state` a (clock, outcome) pair mirrors to — GAME_OVER once the outcome is
	// decided, else the clock state. Keeps the retained column meaningful for a pre-split rollback.
	private static String legacyStateOf(String clockState, String outcome) {
		return Outcome.fromRecord(outcome).isDecided() ? "GAME_OVER"
				: (clockState == null ? "CREATED" : clockState);
	}

	@Override
	public Optional<SessionRecord> find(String id) {
		return jdbc.query("SELECT * FROM game_session WHERE id = ?", MAPPER, id).stream().findFirst();
	}

	@Override
	public List<SessionRecord> all() {
		return jdbc.query("SELECT * FROM game_session ORDER BY created_at, id", MAPPER);
	}

	@Override
	public void seat(SeatRecord s) {
		try {
			jdbc.update("""
					INSERT INTO session_seat(session_id, user_id, colony_name, province_id, seat_order)
					VALUES (?, ?, ?, ?, ?)""",
					s.sessionId(), s.userId(), s.colonyName(), s.provinceId(), s.seatOrder());
		} catch (DuplicateKeyException already) {
			// the UNIQUE constraint did its job — two joins raced, or a player asked twice
			throw new SeatTakenException(s.userId() + " already holds a seat in " + s.sessionId());
		}
	}

	@Override
	public void forget(String id) {
		jdbc.update("DELETE FROM session_seat WHERE session_id = ?", id);
		jdbc.update("DELETE FROM game_session WHERE id = ?", id);
	}

	@Override
	public List<SeatRecord> seats(String sessionId) {
		return jdbc.query("SELECT * FROM session_seat WHERE session_id = ? ORDER BY seat_order",
				SEAT_MAPPER, sessionId);
	}

	@Override
	public Optional<SeatRecord> seatOf(String sessionId, String userId) {
		return jdbc.query("SELECT * FROM session_seat WHERE session_id = ? AND user_id = ?",
				SEAT_MAPPER, sessionId, userId).stream().findFirst();
	}

	private static final RowMapper<SessionRecord> MAPPER = (rs, n) -> new SessionRecord(
			rs.getString("id"), rs.getString("scenario"), rs.getLong("seed"),
			rs.getInt("province_id"), rs.getString("owner"), rs.getString("kind"),
			rs.getString("mode"), rs.getString("difficulty"), rs.getString("clock_state"),
			rs.getString("outcome"), rs.getString("end_reason"), rs.getLong("tick"));

	private static final RowMapper<SeatRecord> SEAT_MAPPER = (rs, n) -> new SeatRecord(
			rs.getString("session_id"), rs.getString("user_id"), rs.getString("colony_name"),
			rs.getInt("province_id"), rs.getInt("seat_order"));
}
