package com.civstudio.server.chat;

import java.util.Collections;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;

import com.civstudio.server.render.ChatMessage;

/**
 * A {@link ChatStore} backed by a {@code chat_message} table via {@link JdbcTemplate}. The schema
 * is created on first use with {@code CREATE TABLE IF NOT EXISTS} (portable across H2 and
 * PostgreSQL), so it is safe to point at a shared database — it touches only its own table. Rows
 * are ordered by an identity id (post order). Mirrors {@code JdbcCommandStore}.
 */
public final class JdbcChatStore implements ChatStore {

	private final JdbcTemplate jdbc;

	public JdbcChatStore(JdbcTemplate jdbc) {
		this.jdbc = jdbc;
	}

	/** Create the table + index if absent. Portable DDL ({@code author}/{@code body} avoid the
	 * reserved words {@code user}/{@code text}). */
	public void initSchema() {
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS chat_message (
				  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  session_id VARCHAR(160) NOT NULL,
				  author     VARCHAR(160) NOT NULL,
				  body       VARCHAR(1000) NOT NULL,
				  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
				)""");
		jdbc.execute("CREATE INDEX IF NOT EXISTS idx_chat_message_session "
				+ "ON chat_message(session_id, id)");
	}

	@Override
	public void append(String sessionId, String user, String text) {
		jdbc.update("INSERT INTO chat_message(session_id, author, body) VALUES (?, ?, ?)",
				sessionId, user, text);
	}

	@Override
	public List<ChatMessage> recent(String sessionId, int limit) {
		// newest-first from SQL (so LIMIT keeps the latest), then reverse to oldest-first for replay
		List<ChatMessage> newestFirst = jdbc.query(
				"SELECT author, body FROM chat_message WHERE session_id = ? ORDER BY id DESC LIMIT ?",
				(rs, rowNum) -> new ChatMessage(rs.getString("author"), rs.getString("body")),
				sessionId, limit);
		Collections.reverse(newestFirst);
		return newestFirst;
	}
}
